### ISSUE TITLE
Issue with pageSize in search API

### ISSUE THREAD

**Issue by 3weTN** [camunda-community-hub/camunda-8-sdk-node-js#23]
I have a node js app and this is my code to call search API :

`
 const queryOptions = {};
queryOptions.pageSize = 1000;

    const tasks = await tasklistAPI.getTasks(queryOptions, [
      "candidateUsers",
      "assignee",
      "candidateGroups",
      "creationTime",
      "completionTime",
      "formKey",
      "id",
      "isFirst",
      "name",
      "processDefinitionId",
      "processInstanceId",
      "processName",
      "taskDefinitionId",
      "taskState",
    ]);`
    
    But when calling api i get this error : 
    "Validation error (WrongType@\[tasks\]) : argument 'query.pageSize' with value 'StringValue{value='10'}' is not a valid 'Int' - Expected an AST type of 'IntValue' but it was a 'StringValue'"
    
    Any help ?

**Comment by jwulf** [comment]
Please try this with the `@camunda8/sdk` package, or the `@camunda8/tasklist` package. This new package supports only the REST API, so your code will require some refactoring.

**Comment by jwulf** [comment]
This client is being archived. In 8.5 we will have a supported Node SDK for Camunda 8: https://github.com/camunda-community-hub/camunda-8-js-sdk
