### ISSUE TITLE
Can not renew expired token

### ISSUE THREAD

**Issue by hanh-le-clv** [camunda-community-hub/camunda-8-sdk-node-js#7]
Currently, we have faced the issue of expired token, so Camunda API returned 401 code after 24 hours.

**Class: OAuthProviderImpl**

- As my understanding, token is stored in memory and file until it;s expired.

For token store in memory object
`const key = this.getCacheKey(audience);
 this.tokenCache[key] = token;`

And function `startExpiryTimer` will check and remove token in memory if it;s expired, but I think we have some issues here:
1. This line of code ` const validityPeriod = token.expiry - current * 1000;` may return incorrect data `validityPeriod`
2. `delete this.tokenCache[this.clientId];` 
     We used `key = clientId + audience` to store tken but used only `clientId to` delete token.

![Screen Shot 2023-10-20 at 10 41 11](https://github.com/camunda-community-hub/camunda-8-sdk-node-js/assets/111100547/395a6870-40e3-4f85-a4bc-2302801c44d3)
![Screen Shot 2023-10-20 at 10 42 54](https://github.com/camunda-community-hub/camunda-8-sdk-node-js/assets/111100547/fff62cc5-5fda-4c41-8eaf-bac7b69ab359)

Please advise more on it. Thank you.

**Comment by jwulf** [comment]
Thanks for reporting this. I'm looking at it now.

**Comment by jwulf** [comment]
I've fixed it in upstream. Now, I need to update the dependencies in the API clients, and republish the SDK package. Standby...

**Comment by jwulf** [comment]
This client is being archived and not maintained. With the 8.5 release we plan to have an officially supported SDK based on this repository: https://github.com/camunda-community-hub/camunda-8-js-sdk
